# Generated by Django 3.2.10 on 2022-12-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0002_rename_subject_encrypt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypt',
            old_name='name',
            new_name='subject',
        ),
    ]
