# Generated by Django 3.2.10 on 2022-12-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projapp', '0004_rename_subject_encrypt_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypt',
            old_name='name',
            new_name='Name',
        ),
    ]
